/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: be45318f9368277d0e0a092056fcecac)
interface __BaseEnv_Env {
	CARD_IMAGES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ADMIN_PASSWORD: string;
	GUEST_PASSWORD: string;
	SESSION_SECRET: string;
	ALLOWED_ORIGIN: string;
	POKEMON_TCG_API_KEY: string;
	POKETRACE_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_PASSWORD" | "GUEST_PASSWORD" | "SESSION_SECRET" | "ALLOWED_ORIGIN" | "POKEMON_TCG_API_KEY" | "POKETRACE_API_KEY">> {}
}
